# Generated by Django 4.2.6 on 2024-04-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='ev_or_is',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
