# Generated by Django 4.2.6 on 2024-05-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_shippingaddress_ev_or_is'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_shipped',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
