# Generated by Django 4.2.6 on 2024-03-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address1',
            new_name='adres1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='address2',
            new_name='adres2',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='old_cart',
            new_name='eski_sepet',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='eyalet',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='country',
            new_name='posta_kodu',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='telefon',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='state',
            new_name='ülke',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='zipcode',
            new_name='şehir',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='profile',
            name='tarih_düzenleme',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
