# Generated by Django 4.2.6 on 2024-03-03 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_address1_profile_adres1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='eyalet',
            new_name='ilce',
        ),
    ]
