# Generated by Django 4.2.6 on 2024-03-03 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_eyalet_profile_ilce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ülke',
            new_name='sehir',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='şehir',
            new_name='ulke',
        ),
    ]
