# Generated by Django 4.2.6 on 2024-03-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_ülke_profile_sehir_rename_şehir_profile_ulke'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='eski_sepet',
            new_name='old_cart',
        ),
    ]
