# Generated by Django 4.2.6 on 2024-03-24 21:27

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_eski_sepet_profile_old_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='adres1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='adres2',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='ilce',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='posta_kodu',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='telefon',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='sehir',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='ulke',
            new_name='zipcode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tarih_düzenleme',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
